### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by NealOKelly** [billpatrianakos/saml2js#5]
HI there,

Thanks so much for putting this together.  Am sure it will save me a load of time on the long run.

But just to let you know, the README.md has a typo, I think, in the section regarding toObject().

The sample code references "asObject()" ... which, of course, isn't a function.

Just spent a good 25 minutes wondering if I was mad or not.

Thanks

Neal

**Comment by billpatrianakos** [comment]
I thought I was going mad looking for this issue. I see it's correct on the master branch but wrong on the develop branch. Thanks for pointing this out. It should be fixed now. Please feel free to open a new issue or do a PR if I missed something.
